# ============================================================
# BIW Failure Recovery Framework
# File: main.py
# Run: python main.py
# RoboDK must be open with SingleRobot.rdk
# ============================================================

import time
import json
import logging
import threading
import signal
import sys
import os
from enum import Enum, auto
from datetime import datetime
from robodk.robolink import Robolink, ITEM_TYPE_ROBOT, ITEM_TYPE_TARGET
from robodk.robomath import pose_2_xyzrpw

# ============================================================
# CONFIG
# ============================================================

# ── Execution path — loaded from path_execution.json at startup ──────────────
# Generated by build_execution_path.py
# Contains named targets AND IW_ intermediates in correct order.
EXECUTION_PATH_FILE = "path_execution.json"

def load_execution_path():
    with open(EXECUTION_PATH_FILE) as f:
        data = json.load(f)
    return data["path"]  # list of {"name", "joints", "type", "note"}


# Exact execution order from Prog1 InstructionList decode
INSPECTION_SEQUENCE = [
    "Target 1", "Target 2", "Target 4", "Target 5", "Target 6",
    "Target 7", "Target 8", "Target 8a", "Target 9", "Target 10",
    "Target 11", "Target 12", "Target 13", "Target 15", "Target 16",
    "Target 17", "Target 18", "Target 11a", "Target 2", "Target 1"
]

# Retreat IW waypoints between anchors (joints only, in retreat order)
# Used by RecoveryPathManager.retreat()
RETREAT_IW_MAP = {
    # anchor_from → anchor_to : [list of IW joint configs in retreat direction]
    ("Target 11", "Target 7"): [
        [-76.63, 35.73, 34.96,   6.46, -64.84, 0.0],  # IW_RET_T11_T7_1
        [-73.3,  32.4,  38.29, -47.49, -38.1,  0.0],  # IW_RET_T11_T7_2
    ],
    ("Target 7",  "Target 4"): [
        [-69.98, 29.74, 49.3, -106.44, -18.69, 0.0],  # IW_RET_T7_T4_1
        [-69.98, 30.4,  56.96,-111.44, -26.03, 0.0],  # IW_RET_T7_T4_2
    ],
    ("Target 4",  "Target 2"): [],   # direct, confirmed clean
    ("Target 2",  "Target 1"): [],   # exit corridor, confirmed clean
}

# Sparse recovery anchors — manually verified safe retreat poses
# R0 = home, increasing index = deeper into inspection zone
RECOVERY_WAYPOINTS = {
    0:  "Target 1",    # home
    2:  "Target 4",    # entry zone
    7:  "Target 7",    # mid-inspection
    14: "Target 11",   # deep zone
    19: "Target 15",   # exit zone
    23: "Target 11a",  # last complex pose
}

# ROI bounds for vehicle validation (mm, world frame)
# Hyryder chassis near-origin — tune these after physical observation
ROI_BOUNDS = {
    "x": (-300.0, 300.0),
    "y": (-1200.0, 0.0),
    "z": (-50.0, 50.0),
}

# Variant configs: bbox deviation tolerance (mm)
VARIANTS = {
    "hyryder_standard": {"x_tol": 50.0, "y_tol": 50.0, "z_tol": 30.0},
    "hyryder_scaled":   {"x_tol": 100.0, "y_tol": 100.0, "z_tol": 60.0},
}

CHECKPOINT_FILE   = "checkpoint.json"
LOG_FILE          = "recovery_log.json"
HEARTBEAT_FILE    = "heartbeat.txt"
MOVE_SPEED_MM_S   = 5.0
WATCHDOG_TIMEOUT  = 8.0    # seconds — robot stuck if no move completes
NETWORK_RETRIES   = 3
NETWORK_RETRY_DELAY = 2.0  # seconds

# ============================================================
# ENUMS
# ============================================================

class State(Enum):
    IDLE           = auto()
    VALIDATING     = auto()
    INITIALIZING   = auto()
    INSPECTING     = auto()
    FAILURE        = auto()
    RECOVERING     = auto()
    REVALIDATING   = auto()
    RESUMING       = auto()
    ABORTED        = auto()
    COMPLETE       = auto()
    MANUAL_OVERRIDE = auto()

class FailureType(Enum):
    NONE             = auto()
    COLLISION        = auto()
    ESTOP            = auto()
    POWER_LOSS       = auto()
    NETWORK_DOWN     = auto()
    PROGRAM_CRASH    = auto()
    ROBOT_STUCK      = auto()
    UNREACHABLE_POSE = auto()
    SINGULARITY      = auto()
    VEHICLE_SHIFTED  = auto()
    VARIANT_CHANGED  = auto()
    IK_FAILURE       = auto()
    UNKNOWN          = auto()

# ============================================================
# LOGGER
# ============================================================

class StructuredLogger:
    def __init__(self, log_file=LOG_FILE):
        self.log_file = log_file
        self.entries = []
        logging.basicConfig(
            level=logging.INFO,
            format="[%(asctime)s] %(levelname)s %(message)s",
            datefmt="%H:%M:%S"
        )
        self.console = logging.getLogger("BIW")

    def log(self, level, event, **kwargs):
        entry = {
            "ts": datetime.now().isoformat(),
            "level": level,
            "event": event,
            **kwargs
        }
        self.entries.append(entry)
        msg = f"{event}" + (f" | {kwargs}" if kwargs else "")
        if level == "ERROR":
            self.console.error(msg)
        elif level == "WARN":
            self.console.warning(msg)
        else:
            self.console.info(msg)
        # Append to file immediately (survive crash)
        with open(self.log_file, "a") as f:
            f.write(json.dumps(entry) + "\n")

    def info(self, event, **kw):  self.log("INFO",  event, **kw)
    def warn(self, event, **kw):  self.log("WARN",  event, **kw)
    def error(self, event, **kw): self.log("ERROR", event, **kw)

# ============================================================
# CHECKPOINT MANAGER
# ============================================================

class CheckpointManager:
    def __init__(self, logger):
        self.logger = logger

    def save(self, pose_index, pose_name, joints):
        tmp = CHECKPOINT_FILE + ".tmp"
        data = {
            "pose_index": pose_index,
            "pose_name":  pose_name,
            "joints_deg": joints,
            "timestamp":  datetime.now().isoformat(),
            "state":      "INSPECTING"
        }
        with open(tmp, "w") as f:
            json.dump(data, f, indent=2)
        os.replace(tmp, CHECKPOINT_FILE)  # atomic write
        self.logger.info("CHECKPOINT_SAVED", pose=pose_name, index=pose_index)

    def load(self):
        if not os.path.exists(CHECKPOINT_FILE):
            return None
        try:
            with open(CHECKPOINT_FILE) as f:
                data = json.load(f)
            self.logger.info("CHECKPOINT_LOADED", data=data)
            return data
        except Exception as e:
            self.logger.error("CHECKPOINT_CORRUPT", error=str(e))
            return None

    def clear(self):
        if os.path.exists(CHECKPOINT_FILE):
            os.remove(CHECKPOINT_FILE)

# ============================================================
# VEHICLE VALIDATOR (placeholder — ROI approach)
# ============================================================

class VehicleValidator:
    def __init__(self, logger, RDK):
        self.logger = logger
        self.RDK = RDK

    def validate(self, variant="hyryder_standard"):
        """
        Production: replace with camera bbox or PLC signal.
        Simulation: check RoboDK object pose within ROI bounds.
        """
        try:
            vehicle = self.RDK.Item("Hyryder chasis_extra studs")
            pose = vehicle.Pose()
            xyzrpw = pose_2_xyzrpw(pose)
            x, y, z = xyzrpw[0], xyzrpw[1], xyzrpw[2]
            in_roi = (
                ROI_BOUNDS["x"][0] <= x <= ROI_BOUNDS["x"][1] and
                ROI_BOUNDS["y"][0] <= y <= ROI_BOUNDS["y"][1] and
                ROI_BOUNDS["z"][0] <= z <= ROI_BOUNDS["z"][1]
            )
            tol = VARIANTS.get(variant, VARIANTS["hyryder_standard"])
            # Nominal position for standard Hyryder
            nominal = {"x": 0.0, "y": -1.4, "z": -0.5}
            within_tolerance = (
                abs(x - nominal["x"]) <= tol["x_tol"] and
                abs(y - nominal["y"]) <= tol["y_tol"] and
                abs(z - nominal["z"]) <= tol["z_tol"]
            )
            self.logger.info("VEHICLE_VALIDATION",
                             xyz=(round(x,2), round(y,2), round(z,2)),
                             in_roi=in_roi, within_tolerance=within_tolerance,
                             variant=variant)
            return in_roi and within_tolerance
        except Exception as e:
            self.logger.error("VEHICLE_VALIDATION_ERROR", error=str(e))
            return False

    def revalidate_mid_inspection(self):
        """Called during recovery to check if vehicle shifted."""
        return self.validate()

# ============================================================
# HEALTH MONITOR (watchdog thread)
# ============================================================

class HealthMonitor:
    def __init__(self, logger):
        self.logger = logger
        self.failure_event = threading.Event()
        self.failure_type  = FailureType.NONE
        self._stop         = threading.Event()
        self._last_pose_time = time.time()
        self._robot_moving = False
        self._thread = threading.Thread(target=self._run, daemon=True)

    def start(self):
        self._thread.start()
        self.logger.info("HEALTH_MONITOR_STARTED")

    def stop(self):
        self._stop.set()

    def notify_move_start(self):
        self._robot_moving = True
        self._last_pose_time = time.time()

    def notify_move_done(self):
        self._robot_moving = False
        self._last_pose_time = time.time()
        self._write_heartbeat()

    def _write_heartbeat(self):
        with open(HEARTBEAT_FILE, "w") as f:
            f.write(datetime.now().isoformat())

    def _check_heartbeat_age(self):
        """Detect power loss on cold restart — heartbeat file too old."""
        if not os.path.exists(HEARTBEAT_FILE):
            return False
        age = time.time() - os.path.getmtime(HEARTBEAT_FILE)
        return age > 30.0  # 30s stale = likely power loss

    def _run(self):
        while not self._stop.is_set():
            time.sleep(1.0)
            if self.failure_event.is_set():
                continue
            # Stuck detection
            if self._robot_moving:
                elapsed = time.time() - self._last_pose_time
                if elapsed > WATCHDOG_TIMEOUT:
                    self.logger.error("WATCHDOG_STUCK_DETECTED",
                                      elapsed=round(elapsed, 1))
                    self.failure_type = FailureType.ROBOT_STUCK
                    self.failure_event.set()

    def signal_failure(self, ftype: FailureType):
        self.failure_type = ftype
        self.failure_event.set()
        self.logger.error("FAILURE_SIGNALED", type=ftype.name)

    def clear(self):
        self.failure_event.clear()
        self.failure_type = FailureType.NONE
        self._subfailure = 1  # subfailure index from inject script

# ============================================================
# RECOVERY PATH MANAGER
# ============================================================

class RecoveryPathManager:
    def __init__(self, logger, RDK, robot):
        self.logger = logger
        self.RDK    = RDK
        self.robot  = robot

    def _get_anchor_at_or_before(self, pose_index):
        """Find nearest recovery anchor <= current pose index."""
        anchors = sorted(RECOVERY_WAYPOINTS.keys(), reverse=True)
        for a in anchors:
            if a <= pose_index:
                return a
        return 0

    def retreat(self, from_pose_index):
        """Step back through execution_path in reverse, one pose at a time."""
        execution_path = load_execution_path()
        self.logger.info("RETREAT_START", from_index=from_pose_index)

        for idx in range(from_pose_index - 1, -1, -1):
            step = execution_path[idx]
            self.logger.info("RETREAT_STEP", index=idx, pose=step["name"])
            try:
                if step["type"] == "iw":
                    self.robot.MoveJ(step["joints"])
                else:
                    target = self.RDK.Item(step["name"], ITEM_TYPE_TARGET)
                    if not target.Valid():
                        self.logger.error("RETREAT_TARGET_INVALID", name=step["name"])
                        return False
                    self.robot.MoveJ(target)
                self.logger.info("RETREAT_STEP_OK", index=idx, pose=step["name"])
                time.sleep(0.2)
            except Exception as e:
                self.logger.error("RETREAT_STEP_FAILED", index=idx, pose=step["name"], error=str(e))
                return False

        self.logger.info("RETREAT_COMPLETE", final="Target 1")
        return True

    def _move_joints(self, joints, label=""):
        """Move to a raw joint config (for IW_ intermediates)."""
        try:
            self.robot.MoveJ(joints)
            self.logger.info("RETREAT_IW_STEP_OK", label=label,
                             joints=[round(j,2) for j in joints])
            return True
        except Exception as e:
            self.logger.error("RETREAT_IW_STEP_FAILED", label=label, error=str(e))
            return False

    def local_safe_offset(self, z_offset_mm=50.0):
        """
        Move TCP straight up by z_offset_mm before retreating.
        Used for collision / stuck scenarios.
        """
        try:
            current_pose = self.robot.Pose()
            xyzrpw = list(pose_2_xyzrpw(current_pose))
            xyzrpw[2] += z_offset_mm
            from robodk.robomath import xyzrpw_2_pose
            offset_pose = xyzrpw_2_pose(xyzrpw)
            self.robot.MoveL(offset_pose)
            self.logger.info("LOCAL_OFFSET_APPLIED", z_offset_mm=z_offset_mm)
            return True
        except Exception as e:
            self.logger.error("LOCAL_OFFSET_FAILED", error=str(e))
            return False

    def _move_to_target(self, target_name):
        try:
            target = self.RDK.Item(target_name, ITEM_TYPE_TARGET)
            if not target.Valid():
                self.logger.error("TARGET_NOT_FOUND", name=target_name)
                return False
            self.robot.MoveJ(target)
            return True
        except Exception as e:
            self.logger.error("MOVE_FAILED", target=target_name, error=str(e))
            return False

# ============================================================
# FAILURE DETECTOR
# ============================================================

class FailureDetector:
    def __init__(self, logger, health_monitor):
        self.logger = logger
        self.hm     = health_monitor

    def classify(self, exception=None) -> FailureType:
        """Map exception or health monitor signal to FailureType."""
        # Health monitor already classified it
        if self.hm.failure_event.is_set():
            return self.hm.failure_type

        if exception is None:
            return FailureType.UNKNOWN

        msg = str(exception).lower()
        if "collision" in msg:
            return FailureType.COLLISION
        if "estop" in msg or "emergency" in msg:
            return FailureType.ESTOP
        if "socket" in msg or "connection" in msg or "timeout" in msg:
            return FailureType.NETWORK_DOWN
        if "ik" in msg or "unreachable" in msg or "no solution" in msg:
            return FailureType.IK_FAILURE
        if "singularity" in msg or "singular" in msg:
            return FailureType.SINGULARITY
        return FailureType.PROGRAM_CRASH

# ============================================================
# RECOVERY MANAGER — policy per failure type
# ============================================================

class RecoveryManager:
    def __init__(self, logger, health_monitor, recovery_path_mgr,
                 vehicle_validator, RDK, robot):
        self.logger    = logger
        self.hm        = health_monitor
        self.rpm       = recovery_path_mgr
        self.validator = vehicle_validator
        self.RDK       = RDK
        self.robot     = robot
        self._network_retry_count = 0

    def recover(self, failure_type: FailureType, pose_index: int) -> str:
        """
        Returns: 'resume' | 'restart' | 'abort' | 'manual'
        """
        self.logger.info("RECOVERY_START",
                         failure=failure_type.name, pose_index=pose_index)

        if failure_type == FailureType.COLLISION:
            return self._recover_collision(pose_index)

        elif failure_type == FailureType.ESTOP:
            return self._recover_estop(pose_index)

        elif failure_type in (FailureType.POWER_LOSS, FailureType.PROGRAM_CRASH):
            return self._recover_power_loss(pose_index)

        elif failure_type == FailureType.NETWORK_DOWN:
            return self._recover_network(pose_index)

        elif failure_type == FailureType.ROBOT_STUCK:
            return self._recover_stuck(pose_index)

        elif failure_type == FailureType.IK_FAILURE:
            return self._recover_ik_failure(pose_index)

        elif failure_type == FailureType.SINGULARITY:
            return self._recover_singularity(pose_index)

        elif failure_type == FailureType.VEHICLE_SHIFTED:
            return self._recover_vehicle_shifted(pose_index)

        elif failure_type == FailureType.VARIANT_CHANGED:
            return self._recover_variant_changed(pose_index)

        else:
            self.logger.warn("UNKNOWN_FAILURE_TYPE", fallback="abort")
            return self._abort()

    # ── Per-failure policies ──────────────────────────────────────────────────

    def _recover_collision(self, pose_index):
        """Local Z offset → retreat → revalidate → resume"""
        self.logger.info("POLICY_COLLISION")
        offset_ok = self.rpm.local_safe_offset(z_offset_mm=60.0)
        if not offset_ok:
            self.logger.error("OFFSET_FAILED_GOING_MANUAL")
            return "manual"
        retreat_ok = self.rpm.retreat(pose_index)
        if not retreat_ok:
            return "manual"
        if self.validator.revalidate_mid_inspection():
            self.logger.info("COLLISION_RECOVERY_OK", action="resume")
            return "resume"
        return self._abort()

    def _recover_estop(self, pose_index):
        self.logger.warn("POLICY_ESTOP")
        retreat_ok = self.rpm.retreat(pose_index)
        if not retreat_ok:
            return "manual"
        self.logger.info("ESTOP_RECOVERY_OK", action="resume")
        return "resume"

    def _recover_power_loss(self, pose_index):
        self.logger.info("POLICY_PROGRAM_CRASH_RECOVERY")
        retreat_ok = self.rpm.retreat(pose_index)
        if not retreat_ok:
            return "manual"
        if self.validator.revalidate_mid_inspection():
            self.logger.info("PROGRAM_CRASH_RECOVERY_OK", action="restart")
            return "restart"
        return self._abort()

    def _recover_network(self, pose_index):
        """Retry RoboDK connection N times → resume or abort"""
        self.logger.warn("POLICY_NETWORK_RETRY")
        for attempt in range(1, NETWORK_RETRIES + 1):
            self.logger.info("NETWORK_RETRY", attempt=attempt)
            time.sleep(NETWORK_RETRY_DELAY)
            try:
                self.RDK.Connect()
                self.logger.info("NETWORK_RECONNECTED", attempt=attempt)
                self._network_retry_count = 0
                return "resume"
            except Exception as e:
                self.logger.error("NETWORK_RETRY_FAILED",
                                  attempt=attempt, error=str(e))
        self.logger.error("NETWORK_EXHAUSTED_RETRIES")
        return self._abort()

    def _recover_stuck(self, pose_index):
        """Watchdog timeout → local offset → retreat → resume"""
        self.logger.info("POLICY_ROBOT_STUCK")
        self.robot.Stop()
        time.sleep(1.0)
        offset_ok = self.rpm.local_safe_offset(z_offset_mm=50.0)
        if not offset_ok:
            return "manual"
        retreat_ok = self.rpm.retreat(pose_index)
        if not retreat_ok:
            return "manual"
        self.logger.info("STUCK_RECOVERY_OK", action="resume")
        return "resume"

    def _recover_ik_failure(self, pose_index):
        """IK failed at pose → skip if non-critical → retreat → resume"""
        self.logger.warn("POLICY_IK_FAILURE", pose_index=pose_index)
        pose_name = INSPECTION_SEQUENCE[pose_index]
        # Non-critical: poses that are supplemental (8a, 11a, 15–18)
        NON_CRITICAL = {"Target 8a", "Target 11a", "Target 15",
                        "Target 16", "Target 17", "Target 18"}
        if pose_name in NON_CRITICAL:
            self.logger.warn("IK_SKIP_NON_CRITICAL", pose=pose_name)
            return "resume"  # caller increments index
        retreat_ok = self.rpm.retreat(pose_index)
        if not retreat_ok:
            return "manual"
        return self._abort()

    def _recover_singularity(self, pose_index):
        """Pre-detected singularity → retreat → abort (no blind retry)"""
        self.logger.error("POLICY_SINGULARITY", pose_index=pose_index)
        self.rpm.retreat(pose_index)
        return self._abort()

    def _recover_vehicle_shifted(self, pose_index):
        """Pause → revalidate ROI → resume if within tolerance else abort"""
        self.logger.warn("POLICY_VEHICLE_SHIFTED")
        retreat_ok = self.rpm.retreat(pose_index)
        if not retreat_ok:
            return "manual"
        if self.validator.validate():
            self.logger.info("VEHICLE_REVALIDATED_OK", action="restart")
            return "restart"
        self.logger.error("VEHICLE_OUT_OF_TOLERANCE")
        return self._abort()

    def _recover_variant_changed(self, pose_index):
        """Variant mismatch → attempt config swap → abort if unknown"""
        self.logger.warn("POLICY_VARIANT_CHANGED")
        # In simulation: try each known variant
        for variant_name in VARIANTS:
            if self.validator.validate(variant=variant_name):
                self.logger.info("VARIANT_MATCHED", variant=variant_name,
                                 action="restart")
                return "restart"
        self.logger.error("VARIANT_UNKNOWN_ABORT")
        self.rpm.retreat(pose_index)
        return self._abort()

    def _abort(self):
        self.logger.error("RECOVERY_DECISION", action="ABORT")
        return "abort"

# ============================================================
# INSPECTION EXECUTOR + STATE MACHINE
# ============================================================

class InspectionExecutor:
    def __init__(self, logger, checkpoint_mgr, health_monitor,
                 failure_detector, recovery_manager, recovery_path_mgr,
                 vehicle_validator, RDK, robot):
        self.logger      = logger
        self.ckpt        = checkpoint_mgr
        self.hm          = health_monitor
        self.fd          = failure_detector
        self.rm          = recovery_manager
        self.rpm         = recovery_path_mgr
        self.validator   = vehicle_validator
        self.RDK         = RDK
        self.robot       = robot
        self.state       = State.IDLE
        self.start_index = 0
        self.failure_index = -1

    def _set_state(self, s: State):
        self.logger.info("STATE_CHANGE",
                         old=self.state.name, new=s.name)
        self.state = s
    
    def _check_signal_file(self):
        """Poll failure_signal.json each pose. Returns (FailureType, subfailure_int) or (None, None)."""
        path = "failure_signal.json"
        if not os.path.exists(path):
            return None, None
        try:
            with open(path) as f:
                sig = json.load(f)
            os.remove(path)  # consume immediately — one-shot
            ftype = FailureType[sig.get("type", "UNKNOWN")]
            sub   = sig.get("subfailure", 1)
            self.logger.warn("SIGNAL_FILE_DETECTED", type=ftype.name, subfailure=sub)
            return ftype, sub
        except Exception as e:
            self.logger.error("SIGNAL_FILE_READ_ERROR", error=str(e))
            return None, None

    def _move(self, target_name):
        target = self.RDK.Item(target_name, ITEM_TYPE_TARGET)
        if not target.Valid():
            raise RuntimeError(f"IK no solution: {target_name}")
        self.hm.notify_move_start()
        self.robot.MoveJ(target)
        self.hm.notify_move_done()
    
    def _move_step(self, step):
        """Move to a named target or raw joint IW_ config."""
        if step["type"] == "iw":
            # IW_ intermediates: move by joint config directly
            self.hm.notify_move_start()
            self.robot.MoveJ(step["joints"])
            self.hm.notify_move_done()
        else:
            # Named target: use existing _move logic
            self._move(step["name"])

    def _pre_singularity_check(self, pose_name, joints):
        """Warn if J5 near 0 (wrist singularity)."""
        if len(joints) >= 5 and abs(joints[4]) < 5.0:
            self.logger.warn("SINGULARITY_PRE_CHECK",
                             pose=pose_name, J5=joints[4])
            return True
        return False

    def run(self):
        # ── State: IDLE → VALIDATING ─────────────────────────────────────────
        self._set_state(State.VALIDATING)
        print("\n" + "="*50)
        print("  BIW Inspection — Failure Recovery Framework")
        print("="*50)

        # Check for cold-restart checkpoint
        ckpt = self.ckpt.load()
        if ckpt:
            print(f"\n[RECOVERY] Cold restart detected.")
            print(f"  Last checkpoint: {ckpt['pose_name']} (index {ckpt['pose_index']})")
            ans = input("  Resume from checkpoint? (y/n): ").strip().lower()
            if ans == "y":
                self.start_index = ckpt["pose_index"]
                self.hm.signal_failure(FailureType.POWER_LOSS)
                # Run power loss recovery inline
                action = self.rm.recover(FailureType.POWER_LOSS, self.start_index)
                if action == "abort":
                    self._set_state(State.ABORTED)
                    return
                if action == "restart":
                    self.start_index = 0
                    self.ckpt.clear()
                self.hm.clear()
            else:
                self.ckpt.clear()

        # Vehicle validation menu
        print("\nIs the vehicle in position and valid?")
        ans = input("  Enter 'yes' to proceed, 'no' to abort: ").strip().lower()
        if ans != "yes":
            print("[ABORT] Vehicle not valid. Exiting.")
            self._set_state(State.ABORTED)
            return

        if not self.validator.validate():
            print("[ABORT] Vehicle failed ROI validation.")
            self.logger.error("VEHICLE_INVALID_ABORT")
            self._set_state(State.ABORTED)
            return

        # ── State: INITIALIZING ──────────────────────────────────────────────
        self._set_state(State.INITIALIZING)
        self.hm.start()
        self.logger.info("INSPECTION_START",
                         total_poses=len(INSPECTION_SEQUENCE),
                         start_index=self.start_index)

        # ── State: INSPECTING ────────────────────────────────────────────────
        self._set_state(State.INSPECTING)
        execution_path = load_execution_path()
        idx = self.start_index
        try:
            while idx < len(execution_path):
                step = execution_path[idx]
                pose_name = step["name"]

                # Poll signal file (injected failures from inject_*.py scripts)
                sig_type, sig_sub = self._check_signal_file()
                if sig_type:
                    self.failure_index = idx  # ← Store the pose index where signal was detected
                    self.hm.signal_failure(sig_type)
                    self.hm._subfailure = sig_sub  # carry subfailure number into handler

                # Check health monitor for async failures
                if self.hm.failure_event.is_set():
                    ftype = self.hm.failure_type
                    # Use stored failure_index, not current idx
                    failure_idx = getattr(self, 'failure_index', idx)
                    self.logger.error("ASYNC_FAILURE_DETECTED",
                                    type=ftype.name, at_pose=pose_name, failure_index=failure_idx)
                    action = self._handle_failure(ftype, failure_idx)
                    if action == "abort":
                        self._set_state(State.ABORTED)
                        return
                    elif action == "manual":
                        self._set_state(State.MANUAL_OVERRIDE)
                        return
                    elif action == "restart":
                        # ── OPTION A: STOP AT HOME, NO RE-INSPECTION ──
                        self.logger.info("RECOVERY_COMPLETE_STOPPED_AT_HOME")
                        self._set_state(State.COMPLETE)
                        self.ckpt.clear()
                        self.hm.stop()
                        self.failure_index = -1
                        return  # ← Exit completely, no re-inspection
                    # resume: continue from current idx
                    self.hm.clear()
                    self.failure_index = -1

                self.logger.info("MOVING_TO", pose=pose_name, index=idx)
                # ── TESTING: Add delay at injection points ──
                if idx in [9, 14, 16, 23]:  # Target 8a, 11, 13, 11a
                    print(f"  [SLOW] Pausing at {pose_name} for 10 seconds...")
                    print(f"  [SLOW] Run inject.py in Terminal 2 NOW!")
                    time.sleep(10.0)
                # ── END TESTING ──
                try:
                    self._move_step(step)
                    # Save checkpoint after every successful move
                    joints = self.robot.Joints().list()
                    self.ckpt.save(idx, pose_name, joints)
                    self.logger.info("POSE_COMPLETE", pose=pose_name, index=idx)

                except KeyboardInterrupt:
                    self.logger.error("KEYBOARD_INTERRUPT", at_pose=pose_name)
                    action = self._handle_failure(FailureType.ESTOP, idx)
                    if action != "resume":
                        self._set_state(State.ABORTED)
                        return
                    self.hm.clear()
                    continue

                except Exception as e:
                    ftype = self.fd.classify(exception=e)
                    self.logger.error("MOVE_EXCEPTION",
                                    pose=pose_name, error=str(e), type=ftype.name)
                    action = self._handle_failure(ftype, idx)
                    if action == "abort":
                        self._set_state(State.ABORTED)
                        return
                    elif action == "manual":
                        self._set_state(State.MANUAL_OVERRIDE)
                        return
                    elif action == "restart":
                        idx = 0
                        continue
                    elif action == "resume":
                        idx += 1  # skip failed pose if non-critical
                        self.hm.clear()
                        continue

                idx += 1
        except Exception as e:
            ftype = self.fd.classify(exception=e)
            self.logger.error("UNHANDLED_EXCEPTION", error=str(e), type=ftype.name)
            self.rpm.retreat(idx)
            self._set_state(State.ABORTED)
            self.hm.stop()
            return
        
        # ── Complete ─────────────────────────────────────────────────────────
        self._set_state(State.COMPLETE)
        self.ckpt.clear()
        self.hm.stop()
        self.logger.info("INSPECTION_COMPLETE")
        print("\n[DONE] Inspection complete. All poses executed successfully.")

    def _handle_failure(self, ftype, idx):
        self._set_state(State.FAILURE)
        self._set_state(State.RECOVERING)
        action = self.rm.recover(ftype, idx)
        if action in ("resume", "restart"):
            self._set_state(State.REVALIDATING)
            if not self.validator.revalidate_mid_inspection():
                self.logger.error("REVALIDATION_FAILED_AFTER_RECOVERY")
                return "abort"
            self._set_state(State.RESUMING)
        return action

# ============================================================
# MAIN
# ============================================================

def main():
    # Connect
    RDK = Robolink()
    if not RDK.Connect():
        print("[ERROR] Cannot connect to RoboDK.")
        sys.exit(1)

    robots = RDK.ItemList(ITEM_TYPE_ROBOT)
    if not robots:
        print("[ERROR] No robot found in station.")
        sys.exit(1)
    robot = robots[0]
    robot.setSpeed(MOVE_SPEED_MM_S)

    # Wire modules
    logger    = StructuredLogger()
    ckpt_mgr  = CheckpointManager(logger)
    hm        = HealthMonitor(logger)
    validator = VehicleValidator(logger, RDK)
    rpm       = RecoveryPathManager(logger, RDK, robot)
    fd        = FailureDetector(logger, hm)
    rm        = RecoveryManager(logger, hm, rpm, validator, RDK, robot)
    executor  = InspectionExecutor(
        logger, ckpt_mgr, hm, fd, rm, rpm, validator, RDK, robot
    )

    # Graceful SIGINT → ESTOP policy
    def sigint_handler(sig, frame):
        logger.error("SIGINT_RECEIVED")
        hm.signal_failure(FailureType.ESTOP)
    signal.signal(signal.SIGINT, sigint_handler)

    executor.run()

    # Print final state
    print(f"\n[STATE] Final: {executor.state.name}")
    print(f"[LOG]   Written to {LOG_FILE}")

if __name__ == "__main__":
    main()